import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: 'docs'}],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api/index'},
      items: [{type: 'autogenerated', dirName: 'api/methods'}],
    },
    {
      type: 'category',
      label: 'Releases',
      link: {
        type: 'generated-index',
        title: 'Release Notes',
        description: 'Published releases of the Ethereum JSON-RPC specification.',
        slug: '/releases',
      },
      items: [{type: 'autogenerated', dirName: 'releases'}],
    },
  ],
};

export default sidebars;

